### ISSUE TITLE
Support aggregated log exports

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-event-function#13]
We are currently only supporting project-level log exports. Log exports can also be aggregated at the folder or organization level: it would be nice to support them.

Suggest using the [terraform-google-log-export](https://github.com/terraform-google-modules/terraform-google-log-export) module that already supports all 3 log exports, and soon will support billing-level log exports as well.

Additionally, sometimes users want to export logs from the GSuite Admin APIs: we recommend using the [terraform-google-gsuite-export](https://github.com/terraform-google-modules/terraform-google-log-export) for this use case.

**Comment by aaron-lane** [comment]
Fixed by #18.
