### ISSUE TITLE
Add support for Terraform 0.12

### ISSUE THREAD

**Issue by aaron-lane** [terraform-google-modules/terraform-google-event-function#20]

**Comment by bohdanyurov-gl** [comment]
- Migrate to the new TF 0.12 syntax
- Add type for variables
- Remove instances of unnecessary string interpolation from the code base
- Remove unnecessary "element" calls
- Run tests locally 
- Switch to docker image for terraform 0.12 (version 2.0.0)
- Update CHANGELOG.md
- Update READMEmd, add latest 0.11 release

**Comment by bohdanyurov-gl** [comment]
@aaron-lane please note that I can not fully fix linter, as it fails on dependent module:
terraform-google-modules/log-export/google
