### ISSUE TITLE
Tests are broken on master

### ISSUE THREAD

**Issue by bohdanyurov-gl** [terraform-google-modules/terraform-google-event-function#21]
Both make check and make docker_verify fail

**Comment by bohdanyurov-gl** [comment]
![image](https://user-images.githubusercontent.com/47155283/61491133-37b18180-a9b7-11e9-99fb-31c7a2491308.png)

**Comment by bohdanyurov-gl** [comment]
Regarding integration tests:
Looks like REGION and ZONE env variables are required. We should probably add a note to README with a link to integration.sh file

**Comment by bohdanyurov-gl** [comment]
On the second though, tests shouldn't probably fail if some parameter that has default is not set

**Comment by morgante** [comment]
@bohdanyurov-gl Indeed! Tests should always pass without overriding default values.

**Comment by bohdanyurov-gl** [comment]
Makefile was outdated (ignored test/integration.sh). Fixed in this PR:
https://github.com/terraform-google-modules/terraform-google-event-function/pull/23

**Comment by bohdanyurov-gl** [comment]
![image](https://user-images.githubusercontent.com/47155283/61567304-ba097680-aa87-11e9-8ea5-04c26e62d0d8.png)
