### ISSUE TITLE
Add example and tests for project-related events

### ISSUE THREAD

**Issue by nick4fake** [terraform-google-modules/terraform-google-event-function#30]
Relevant issues:
https://github.com/terraform-google-modules/terraform-google-vpc-service-controls/issues/11
https://github.com/terraform-google-modules/terraform-google-event-function/issues/27

We need to have an event function for automatic project labeling in a folder.

**Comment by nick4fake** [comment]
Blocked by https://github.com/terraform-google-modules/terraform-google-event-function/issues/27

**Comment by morgante** [comment]
Why do we need examples and tests for this? #27 already added support for listening to events on a folder.

It is *not* necessary that we have explicit examples and tests for every conceivable event.
