### ISSUE TITLE
Support for vpc_connector

### ISSUE THREAD

**Issue by schirayu** [terraform-google-modules/terraform-google-event-function#55]
The terraform resource supports a [vpc_connector ](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function#vpc_connector). It would be great to include it in the module as well. We've had to make a custom change to use this in our environment. Would be great to avoid drift from the original module.

**Comment by bharathkkb** [comment]
@schirayu we would be happy to accept a PR to expose this
