### ISSUE TITLE
Cloud Function deployment fails with "Failed to retrieve function source code"

### ISSUE THREAD

**Issue by yeweidaniel** [terraform-google-modules/terraform-google-event-function#82]
### TL;DR

We are seeing some flakes in creating Cloud Functions with a generic "Failed to retrieve function source code" error message. Can we improve the error message to indicate what is wrong?

### Expected behavior

Succeed or output a message that is useful to troubleshoot.

### Observed behavior

The message is too generic. The same deployment has passed before, and we don't know what is causing this flake.

### Terraform Configuration

```hcl
module "batch_cf" {
  source                = "terraform-google-modules/event-function/google//modules/repository-function"
  version               = "2.1.0"
  name                  = "batch-function"
  project_id            = module.project.project_id
  description           = "Cloud Function to initiate batch pipeline"
  timeout_s             = 540
  entry_point           = "launch_batch_pipeline"
  service_account_email = "${google_service_account.function_runner.account_id}@${module.project.project_id}.iam.gserviceaccount.com"

  source_repository_url = "https://source.developers.google.com/projects/<myproject>/repos/<myrepo>/fixed-aliases/v1.0.0"
  runtime               = "python37"

  region = "us-central1"

  event_trigger = {
    event_type                         = "google.storage.object.finalize"
    resource                           = "<mybucketname>"
    event_trigger_failure_policy_retry = true
  }

  environment_variables = {
    LOCATION                   = "us-central1"
    TEMPLATE_FILE_GCS_LOCATION = "gs://<path to file>.json"
  }
}
```

### Terraform Version

```sh
0.14.8
```

**Comment by bharathkkb** [comment]
@yeweidaniel What provider version are you using? This is a provider issue and IIRC they added retries for this operation which reduced the flakiness.

**Comment by yeweidaniel** [comment]
I am using google provider 3.88, will log an issue there thanks.

**Comment by yeweidaniel** [comment]
Logged https://github.com/hashicorp/terraform-provider-google/issues/10734
